<div style="margin-bottom:40px;">
	<label for="attribute-pic" class="right-flow" id="attribute-pic-label"  style="margin:0px 0px 10px 8px;border: 1px solid #f0f0f0;position:relative">
		<img src="<?php echo DEFAULT_IMAGE?>" class="attribute-thumb" style="display:block" height="160" width="160">
		<div  id="upload-overlay" style="cursor:pointer;position:absolute;top:0px;left:0px;width:100%;height:100%;opacity:0.6;  background: rgb(129, 129, 129);"></div>
		<form method="POST" style="display:none" enctype="multipart/form-data">
			<input id="attribute-pic" class="hdn-input" type="file" name="attribute-pic" title="Add a photo" onchange="loadPic(this)">
		</form>
	</label>
	<div class="inline-blk">
		<div style="margin-bottom:10px;">
			<div style="margin-bottom:4px;">Attribute Name (WHITE, BLACK, ETC)</div>
			<div><input id="attribute-name" type="text" class="fcy-txt" ></div>
		</div>
	
		<div style="margin-bottom:20px;">
			<div style="margin-bottom:4px;">Available Quantity</div>
			<div><input  id="available-quantity" type="text" class="fcy-txt" ></div>
		</div>
	
		<div>
			<div>
				<select  id="available-size" class="left-flow" onchange="checkSettable(this)">
					<option>AVAILABE SIZE</option>
					<?php $available_sizes = $product_size->getAvailableSize(); ?>
					<?php  if($available_sizes !== false):?>
						<?php  foreach($available_sizes  as $size): ?>
							<option><?php echo $size['size']; ?></option>
						<?php endforeach; ?>
					<?php endif; ?>
				</select>
				<div class="inline-blk right-flow" style="margin-right: 6px;" >Set as cover<input id="cover-check" type="checkbox"style="margin-left:6px;" /></div>
			</div>
		</div>
	</div>
</div>			