<div id="detail-info-inner" style="">
	<div style="width:100%;border-bottom:1px solid #eaeaea;"><input id="new-product-title" class="" type="text"  placeholder="Title for the product" style="border:0px;width:90%;font-size:15px;padding:12px 24px;"/></div>
	<div style="width:100%;border-bottom:1px solid #eaeaea"><textarea id="new-product-desc" type="text"  placeholder="Description for the product" style="border:0px;width:90%;font-size:15px;padding:12px 24px;height:140px"></textarea></div>
	<div style="width:100%;"><input id="new-product-price" type="text"  placeholder="Price for the product" style="border:0px;width:90%;font-size:15px;padding:12px 24px;"/></div>
</div>