<div id="popup-dialog" class="dialog inline-blk popup-dialog">
	<div class="dialog-header" style="background:none;border-bottom:1px solid #EAEAEA">
		<div class="dialog-header-inner vertical-center">
			<div class="inline-blk left-align dialog-header-left-item"><div class="bar-title" style="color:#8F2727;font-weight:500;font-size:18px;margin-left:24px;"></div></div>
		</div>
	</div>
	<div class="dialog-body">
		<div class="body-text" style="margin:14px 24px">
		</div>
	</div>
	<div class="edit-dialog-footer dialog-footer">
		<div class="alert-message a-red hdn"></div>
		<div class="inline-blk silver-button cancel-button popup-button animated-button dismiss" style="margin-right:6px" ></div>
		<div class="inline-blk action-button popup-button animated-button red-action-button hdn" style="margin:0px 10px 0px 0px;color:#8F2727" ></div>
	</div>
</div>
