<form action="<?php echo ADMIN_PAGE ?>/admin_login_validation.php"  method="POST" >
	<div style="margin-bottom:10px;"><input type="text" name="username" style="padding:6px;border:1px solid #eaeaea;width:260px;font-size:16px;" placeholder="Username"/></div>
	<div><input type="password" name="password" style="padding:6px;border:1px solid #eaeaea;width:260px;font-size:16px;" placeholder="Password"/></div>
	<div class="" style="padding:16px 14px;"><input type="submit" class="fashion-black-button" name="submit"  value="Login" style="width:100%" /></div>
</form>