<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
	<title>Admin Login</title>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo ROOTDIR?>media/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR?>css/core.css">
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR?>css/admin.css">


	<script type="text/javascript" src="<?php echo ROOTDIR?>js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/core.js"></script>
	
	<!--[if lt IE 9]>
	<script src="dist/html5shiv.js"></script>
	<![endif]-->
	</head>
	<body class="glob-container" style="background-color:#F8F8F8">
		
		<div id="title" style="text-align:center"><a href="<?php echo ROOTDIR ?>index.php" ><div class="inline-blk" id="logo">UNIQUEHYPECOLLECTION</div></a></div>

		<div style="margin:0px auto;width:300px;text-align:center;margin-top:100px">
			<?php echo $admin_body; ?>
		</div>
 	</body>
	
</html>



