<div style="margin-bottom:20px;">Subtotal: <div class="inline-blk" style="margin-left:40px;"><?php echo getCurrencyFormat($subtotal); ?></div></div>
<div>
	<a href="<?php echo ROOTDIR ?>"><button class="fashion-gray-button" id="keep-shopping" style="margin-right:4px;vertical-align:top">Keep Shopping</button></a>
	<button class="fashion-black-button paypal-checkout" id="checkout" style="width:200px;height:40px;"></button>
</div>
