<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
	<title>UniqueHypeCollection</title>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo ROOTDIR?>media/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR?>css/core.css">
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/core.js"></script>
	
	<!--[if lt IE 9]>
	<script src="dist/html5shiv.js"></script>
	<![endif]-->
	</head>
	<body class="glob-container" class="slide-view" style="padding-top: 30px">
		
		
		<?php include_once 'global_header.php'; ?>
		<div class="additional-info" style="font-size:14px;margin-top:10px;text-align:center">Home</div>
		<div id="product-grid">
			<?php echo $products_list; ?>
		</div>		
	</body>	
</html>