<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
	<title>Order Confirm</title>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo ROOTDIR?>media/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR?>css/core.css">

	<script type="text/javascript" src="<?php echo ROOTDIR?>js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/core.js"></script>
	
	<!--[if lt IE 9]>
	<script src="dist/html5shiv.js"></script>
	<![endif]-->
	</head>
	<body class="glob-container">
		<?php include_once 'global_header.php'; ?>
		<div class="additional-info" style="font-size:14px;margin-top:30px;text-align:center">Order Confirmation</div>

		<div style="width:100%;text-align:center">
			<div id="glob-checkout-wrapper" >
				<div style="margin:20px;">
					<div class="order-general-info-wrapper" style="height:240px;">
						<div class="a-red" style="font-size:22px;">ORDER INFORMATION </div>
						<div style="font-size:14px;" >Thank you for your purchase on UniqueHypeCollection, and your order has been placed. You will receive a confirmation email shortly.</div>
						<div class="shpping-addr" style="font-size:14px;margin-top:20px;" >
							<div style="font-weight:600;">Shipping Address</div>
							<div><?php echo $shipping_address; ?></div>
						</div>
						
						<div class="order-refer" style="font-size:14px;margin-top:20px;" >
							<div style="font-weight:600;">Order Number</div>
							<div><?php echo $payment_id; ?></div>
						</div>
					</div>
					<div class="order-detail-wrappr">
						<div class="a-red" style="font-size:22px;">ORDER DETAIL </div>
						<div class="header" style="padding:0px;font-size:0px;border-bottom:1px solid #CDCDCD">
							<div class="form-title grid-column" style="width:60%;text-align:left">Item Description</div>
							<div class="form-title grid-column" style="width:20%;text-align:center">Quantity</div>
							<div class="form-title grid-column" style="width:20%;text-align:right">Price</div>
						</div>
						<div class="body" style="font-size:0px;min-height:156px;">
							<?php echo $order_detail; ?>
							
						</div>
						<div class="footer" style="text-align:right;border-top:1px solid #eaeaea;padding:10px 0px;">
							<div style="margin-bottom:20px;">Total: <div class="inline-blk" style="margin-left:40px;"><?php echo getCurrencyFormat($total); ?></div></div>
						</div>
					</div>
				</div>
 			</div>
		</div>
 	</body>
	
</html>



