<div class="" style="padding:0px 20px;">
		<div class="header" style="padding:0px;font-size:0px;border-bottom:1px solid #CDCDCD">
			<div class="form-title grid-column" style="width:40%;text-align:left">Item Description</div>
			<div class="form-title grid-column" style="width:20%;text-align:center">Quantity</div>
			<div class="form-title grid-column" style="width:20%;text-align:center">Status</div>
			<div class="form-title grid-column" style="width:20%;text-align:right">Price</div>
		</div>
		<div class="body" style="font-size:0px;min-height:256px;">
			<form id="global-checkout-form">
				<?php echo $checkout_body_content; ?>
			</form>
		</div>
		<div class="footer" style="text-align:right;border-top:1px solid #eaeaea;padding:10px 0px;">
			<?php echo $checkout_footer_content; ?>
		</div>
</div>