<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">

	<title><?php echo $product_title; ?></title>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo ROOTDIR?>media/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR?>css/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR?>css/shop.css">

	<script type="text/javascript" src="<?php echo ROOTDIR?>js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/core.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR?>js/shop.js"></script>
	
	<!--[if lt IE 9]>
	<script src="dist/html5shiv.js"></script>
	<![endif]-->
	</head>
	<body class="glob-container">
		<?php include_once 'global_header.php'; ?>
		<div class="additional-info" style="font-size:14px;margin-top:10px;text-align:center">Shop</div>
		<div id="product-preview-wrapper">
			<?php echo $product_preview; ?>
			
		</div>		

 	</body>
	
</html>